# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=20)),
                ('install_date', models.DateTimeField(verbose_name='date installed')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='cctvFile')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('CCTV_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cctv.CCTV')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=20)),
                ('phonenum', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('obj_id', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('obj_color', models.CharField(max_length=20)),
                ('file_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cctv.Files')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('connects', models.ManyToManyField(to='cctv.Neighborhood')),
                ('last', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last', to='cctv.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Shoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CCTV_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cctv.CCTV')),
            ],
        ),
        migrations.CreateModel(
            name='Shoot_space',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dong', models.CharField(max_length=20)),
                ('building_name', models.CharField(max_length=20)),
                ('flr', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.IntegerField()),
                ('time_length', models.IntegerField()),
                ('obj_num', models.IntegerField()),
                ('avg_speed', models.DecimalField(decimal_places=2, max_digits=20)),
                ('avg_size', models.DecimalField(decimal_places=2, max_digits=20)),
                ('file_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cctv.Files')),
            ],
        ),
        migrations.AddField(
            model_name='shoot',
            name='Shoot_space_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cctv.Shoot_space'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='space_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='A', to='cctv.Shoot_space'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='space_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='B', to='cctv.Shoot_space'),
        ),
        migrations.AddField(
            model_name='files',
            name='Shoot_space_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cctv.Shoot_space'),
        ),
        migrations.AddField(
            model_name='cctv',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cctv.Manager'),
        ),
        migrations.AddField(
            model_name='cctv',
            name='shoots',
            field=models.ManyToManyField(through='cctv.Shoot', to='cctv.Shoot_space'),
        ),
    ]
