# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=20)),
                ('pos', models.CharField(max_length=20)),
                ('phonenum', models.CharField(max_length=13)),
            ],
        ),
    ]
